### PR TITLE
Update toolbox.php

### PR DESCRIPTION
**Pull request by SinyaWeo**
Did not display any of the plugin options (no rcmail_action class).

### CODE REVIEW

**Comment by gianlucagiacometti** [comment]
This does not work with last version 1.4.10 (where rcmail_action:: is mandatory)
I changed it two days ago for that reason.
I don't want to go back.

**Comment by SinyaWeo** [comment]
That is strange. I have fresh install of 1.4.10 and had to change it so your plugin can work. Looked in rcmail_action.php in RC source and the class is abstract, so I'll investigate further.

**Comment by gianlucagiacometti** [comment]
Well, I'm using the git updated version (I update it every twice a week), so maybe you're right with version 1.4.10 and it was changed just after the release, because in my git version I was forced to add it.
I think we can go back striping rcmail_action:: out because I wrote that the plugin is working with version 1.4.10. I anyway need to add a big notice for people using the git version.
I appreciated the chance introducing "actions" in roundcube, but I think it's still in progress.
I can do like this. I will delete and re-publish the release 1.4.10-0 and open a new branch 1.4.11.
Thank you

**Comment by SinyaWeo** [comment]
I found it. rcmail_action class is missing in official download package from roundcube.net.
When added manually, your plugin works as intended.

**Comment by gianlucagiacometti** [comment]
Great. I created the branch 1.4.10 without rcmail_action:: and I kept the master updated with Git with a note on the readme.
I guess that's better if people is using official 1.4.10 release of RC like you did.

**Pull request merged**
